WORD_BANK = {
    "fruits": {
        "easy": [
            "APPLE","PEAR","MANGO","KIWI","PLUM","LIME","FIG","DATE","GRAPE","MELON",
            "LEMON","OLIVE","GUAVA","PAPAW","BERRY","APRICOT","TOMATO","POME","PRUNE","BILBERRY",
            "NECTAR","RAISIN","LOQUAT","YUZU","MANDARIN","UGLI","CITRON","CHERRY","PEACH","LYCHEE"
        ],
        "medium": [
            "ORANGE","PAPAYA","AVOCADO","PASSION","CLEMENT","TANGERIN","PLANTAIN","BREADFRU","FEIJOA","SANTOL",
            "DAMSON","ETROG","LONGAN","MIRACLEF","ACKEE","CARISSA","BAYBERRY","BREADNUT","JOSTABER","KEIAPPLE",
            "NANCE","OSAGE","ROSEHIP","SAPODILL","TANGELO","WAXAPPLE","XIGUA","YANGMEI","QUINCE","BARBADOS"
        ],
        "hard": [
            "POMEGRANATE","MANGOSTEEN","CUSTARDAPPLE","JABOTICABA","ACKEEFRUIT","QUANDONG","UGNIFRUIT","VOAVANGA","XIGUAFRUIT","YERBAFRUIT",
            "ZIZIPHUS","DELICIOUS","FINGERLIME","ILAMAFRUIT","JOSTABERRY","KIWANO","LAPSANG","MAMEY","NARANJILLA","PAPAWTREE",
            "RAMBUTANUS","SALAKFRUIT","TAMARILLO","UGLI_FRUIT","VITEX","WAMPANOAG","XANTHIA","ZEDOARY","BILBERRYFR","CARAMBOLA"
        ]
    },
    "animals": {
        "easy": [
            "CAT","DOG","COW","CROW","FROG","HEN","PIG","ANT","BEE","BAT",
            "FOX","APE","DEER","SEAL","SWAN","GOAT","LAMB","KITTY","PUPPY","MOUSE",
            "RAT","BIRD","WOLF","TOAD","MULE","EMU","LYNX","CRAB","DOVE","PONY"
        ],
        "medium": [
            "TIGER","GIRAFFE","RABBIT","DONKEY","PENGUIN","OTTER","HEDGEHOG","PORPOISE","PELICAN","JELLYFISH",
            "KOALA","LEMUR","LLAMA","MARMOT","MEERKAT","OPOSSUM","PORCUPIN","QUOKKA","RACCOON","SQUIRREL",
            "TAPIR","URIAL","VULTURE","WALRUS","XANTUS","YAK","ZEBRA","BANDICOOT","CARIBOU","DINGO"
        ],
        "hard": [
            "CHAMELEON","PORCUPINE","ARMADILLO","HIPPOPOTAMUS","AXOLOTL","BASILISK","CASSOWARY","DUGONG","ECHIDNA","FALCONET",
            "GAVIAL","LORIKEET","MUSKDEER","PANGOLIN","QUOLL","RACCOONDOG","SAOLA","TAPIRUS","URUTU","VICUNA",
            "WOLVERINE","XENOPUS","YAPOK","ZORILLA","ANTELLOPE","BINTURONG","COATI","DHOLE","FOSSA","GIBBON"
        ]
    },
    "cities": {
        "easy": [
            "OSLO","PARIS","ROME","LIMA","MIAMI","TOKYO","DELHI","SEOUL","CAIRO","DUBAI",
            "LA","BALI","LONDON","BERLIN","MADRID","ZURICH","BANGKOK","RIO","DALLAS","PRAGUE",
            "KYIV","OSAKA","LUCCA","MALTA","ZAGREB","MALMO","BRNO","KOBE","TOLEDO","KIGALI"
        ],
        "medium": [
            "DUBLIN","BOSTON","MADRID","PRAGUE","SYDNEY","MUNICH","LISBON","VIENNA","BRUSSELS","HAMBURG",
            "COLOGNE","MONTREAL","SEATTLE","PHOENIX","ATLANTA","BIRMINGHAM","BUDAPEST","COPENHAGEN","FLORENCE","MELBOURNE",
            "SANTIAGO","GUANGZHOU","STOCKHOLM","FARGO","NANTES","TALLINN","KRAKOW","VALENCIA","ROTTERDAM","AMSTERDAM"
        ],
        "hard": [
            "ULANBATOR","CONAKRY","ANTANANARIVO","KATHMANDU","TABRIZ","DJIBOUTI","DURBAN","VILNIUS","UYO","KONYA",
            "TSURUOKA","QINGDAO","XIAN","YANGON","ZAGREB_CITY","BISMARCK","CHISINAU","DZONGKHAG","EXETER","FUKUOKA",
            "GANDHINAGAR","HERAKLION","ISLAMABAD","JOHANNESBURG","LIMERICK","MONTERREY","NARVIK","ODENSE","PESCARA","QUITO"
        ]
    },
    "profession": {
        "easy": [
            "NURSE","TEACHER","BAKER","WAITER","DRIVER","COOK","FARMER","FISHER","CLERK","DOCTOR",
            "POLICE","PLUMBER","PAINTER","BARBER","CHEF","DENTIST","CARPENTER","TAILOR","CASHIER","GARDENER",
            "JANITOR","SECRETARY","RECEPTION","BUTCHER","MECHANIC","MASON","TUTOR","LIBRARIAN","PARAMEDIC","BREWER"
        ],
        "medium": [
            "ENGINEER","DESIGNER","ACCOUNTANT","LAWYER","ARCHITECT","ELECTRICIAN","PROGRAMMER","ANALYST","SURGEON","VETERINARIAN",
            "BLOGGER","CONSULTANT","EDITOR","TRANSLATOR","PHOTOGRAPHER","PLANNER","RESEARCHER","NUTRITIONIST","DIETICIAN","SOCIOLOGIST",
            "BIOLOGIST","CHEMIST","PHYSICIST","STATISTICIAN","AUDITOR","AGRONOMIST","CARDIOLOGIST","DATAENGINEER","DEVOPS","TESTER"
        ],
        "hard": [
            "PHARMACIST","ASTRONAUT","MICROBIOLOGIST","PSYCHOLOGIST","ELECTRICIANMASTER","NEUROSURGEON","COSMOPOLITANIST","ORTHOPAEDIST","TOXICOLOGIST","HYDROGEOLOGIST",
            "IMMUNOLOGIST","KARDIOLOGIST","LIPIDOLOGIST","METEOROLOGIST","NANOTECHNOLOGIST","OPHTHALMOLOGIST","PROSTHETIST","QUANTUMPHYSICIST","RHEUMATOLOGIST","TELEMETRIST",
            "URBANIST","VACCINOLOGIST","WATERRESOURCESENG","XENOBIOTICIAN","YEASTTECHNOLOGIST","ZYMURGYEXPERT","AUDIOENGINEER","CYTOGENETICIST","DENDROLOGIST","ENDODONTIST"
        ]
    }
}
